services:
  - type: web
    name: chatbot-psicologo
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /webhook/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_PROJECT_ID
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: TWILIO_CONTENT_SID
        sync: false
      - key: DEFAULT_RECIPIENT
        sync: false

